apiVersion: v1
kind: Service
metadata:
  name: apache-hello-world
spec:
  selector:
    app: apache-hello-world
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
